project:
  type: website
  output-dir: docs
  
website:
  title: "Onkar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://x.com/onkartweets
      - icon: github
        href: https://github.com/onkaronkar4/profile
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Onkar Singh"

format:
  html:
    theme: cerulean
    toc: true

editor: source

